### ISSUE TITLE
Allow to set an image instead of an icon in Android notifications

### ISSUE THREAD

**Issue by FdezRomero** [arnesson/cordova-plugin-firebase#100]
Hello,

Since this plugin cannot co-exist with `phonegap-plugin-push`, I'm missing the possibility of showing an image from a URL defined in the data payload instead of the default notification icon (a.k.a. `smallIcon`) in Android notifications.

From the [phonegap-plugin-push Payload page](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images):

> The third is the remote *URL*. This JSON sent from GCM:
> 
> ```javascript
> {
>     "registration_ids": ["my device id"],
>     "data": {
>     	"title": "Large Icon",
>     	"message": "Loaded from URL",
>     	"image": "https://dl.dropboxusercontent.com/u/887989/antshot.png"
>     }
> }
> ```
> 
> Here is an example using node-gcm that sends the above JSON:
> 
> ```javascript
> var gcm = require('node-gcm');
> // Replace these with your own values.
> var apiKey = "replace with API key";
> var deviceID = "my device id";
> var service = new gcm.Sender(apiKey);
> var message = new gcm.Message();
> message.addData('title', 'Large Icon');
> message.addData('message', 'Loaded from URL');
> message.addData('image', 'https://dl.dropboxusercontent.com/u/887989/antshot.png');
> service.send(message, { registrationTokens: [ deviceID ] }, function (err, response) {
> 	if(err) console.error(err);
> 	else 	console.log(response);
> });
> ```
> 
> Produces the following notification.
> 
> ![2015-07-24 02 17 55](https://cloud.githubusercontent.com/assets/353180/8866900/2df0ab06-3190-11e5-9a81-fdb85bb0f5a4.png)

Thanks!

**Comment by levibn** [comment]
Hello,
I actually miss this incredibly feature in this awesome plugin.
Hope we can have this soon as possible!
Thanks!

**Comment by alexislg2** [comment]
I agree. See https://github.com/arnesson/cordova-plugin-firebase/issues/250

**Comment by lucasdavila** [comment]
Hey guys, I am thinking about using `cordova-plugin-firebase`, since it supports more firebase features, than `phonegap-plugin-push` that is only for push notifications.

But I noticed it not support showing the image sent on the notification yet.

I saw that there is at least one PR (https://github.com/arnesson/cordova-plugin-firebase/pull/296) that aim to add this feature, but it wasn't merged yet.

Do you have any plans to implement this feature?

In case the feature is already implemented, please let me know.

Thank you.
