### ISSUE TITLE
tap flag not available when we click on notification when the app is in background

### ISSUE THREAD

**Issue by gaurav112** [arnesson/cordova-plugin-firebase#115]
when I logged the content of the notificaiton this is what i got

{"google.sent_time":1481204971734,"collapse_key":"com.gots.attendica","from":"860004433605","google.message_id":"0:1481204971767129%a8f39df3a8f39df3"} 

any suggestions ??

**Comment by saghul** [comment]
Same here

**Comment by lukelovespace** [comment]
+1

**Comment by pedrosobral** [comment]
# [How a push notification works](https://github.com/fechanique/cordova-plugin-fcm/blob/master/README.md#how-it-works)

### Send a push notification to a single device or topic.

- **1.a Application is in foreground:**
    - The notification data is received in the JavaScript callback without notification bar message (this is the normal behaviour of mobile push notifications).
- **1.b Application is in background or closed:**
    - The device displays the notification message in the device notification bar. 
    - If the user taps the notification, the application comes to foreground and the notification data is received in the JavaScript callback.
     - If the user does not tap the notification but opens the applicacion, nothing happens until the notification is tapped.

**1.a** is the only case where the tap property will be set to **false**, otherwise you can assume that the user taps on the notification.

**Comment by elewin** [comment]
That doesn't help though; there are 4 possible outcomes:
Android BG: tap property does not exist
iOS BG: tap: true

Android FG: tap property does not exist
iOS FG: tap: false

so if you were to do a simple 
`
if(tap){
// foreground action 
}else{
//background action
}
`

Then it would work on iOS, but the foreground action would never fire for Android since its always falsey

How else can we discern the difference between the two?

**Comment by jcamilorm902** [comment]
@pedrosobral documentation says that, but real behavior is this issue report. It is missing `tap flag to true`.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
