### ISSUE TITLE
Real time database support

### ISSUE THREAD

**Issue by sleever** [arnesson/cordova-plugin-firebase#156]
Hello everybody,

I was wondering when support for the real time database is being added to this plugin to make it more complete. Of course there are several other plugins like AngularFire and cordova-plugin-firebase-realtime-database but it would be more convenient to have everything in one place.

Thanks in advance for your response.

**Comment by prantikv** [comment]
👍 
Adding to this the **AngularFire ** is not a plugin for cordova but more of a library for firebase+angluar. 
And the **cordova-plugin-firebase-realtime-database ** is not added to Ionic Native.

As this plugin is added to Ionic 2 Native, would love to see the real-time database added here as well.

**Comment by thedmeyer** [comment]
Bumping for visibility. 

Also, would there be any conflicts if I were to use cordova-plugin-firebase in conjunction with cordova-plugin-firebase-realtime-database?

**Comment by Sampath-Lokuge** [comment]
Any feedback for this from the creator of the plugin? Will we have real time database support on this plugin? Thanks.

**Comment by thedmeyer** [comment]
@Sampath-Lokuge I have since switched to https://github.com/firebase/angularfire/ for realtime database support.

I still use cordova-plugin-firebase for direct interactions with remote config, push notifications, and analytics.

**Comment by Sampath-Lokuge** [comment]
Yes.But still, you cannot use it for offline use case no? I think that is the key issue of this plugin. We can do almost all the other things plus more without this plugin if we use firebase JS API. But that API doesn't support offline use case.That is the huge issue right now when we're dealing with the firebase and Ionic app development. Thank you so much for your feedback @thedmeyer

**Comment by thedmeyer** [comment]
@Sampath-Lokuge Take a look at this card. https://github.com/firebase/angularfire/issues/31

Angularfire can support offline use cases to some extent, but not fully. Best practice for implementation would be to load data when available and only write data using isolated set and push calls. (NOT using `$firebaseArray` `$add` and `$save` calls).

This would prevent data from being overwritten in the case that the offline user tries to push out-of-date data when they regain connectivity (since the array loaded offline could have been modified during this period).

See: https://github.com/firebase/angularfire/blob/master/docs/reference.md

Isolated calls: 
https://firebase.google.com/docs/reference/js/firebase.database.Reference#push

**Comment by prantikv** [comment]
I agree with @thedmeyer  I pulled up [this ](https://github.com/driftyco/ionic-native/issues/608)issue with ionic native. As you can see from the reply they won't be adding the other two plugins to the Ionic Native repo, the reason being that they are not popular. Also, taking a look at the repo of cordova-plugin-firebase-realtime-database the plugin does not seem to be under active maintenance.

As a result, I have shifted to AngularFire 2 for my needs and haven't looked back. Best part about using AngularFire2 are observable.

Still would love to see a all-in-one plugin for firebase. Hope this plugin evolves into one.

**Comment by yyzhou1994** [comment]
I tried implement both cordova-firebase-plugin and cordova-firebase-plugin-realtime-database into my cordova project but it returns "google-services.json/GoogleService-Info.plist already exists" error once I start the build. 

I guess it's because both plugins are installing same source files so I commented out `<source-file src="src/android/google-services.json" target-dir="." />` and `<resource-file src="src/ios/GoogleService-Info.plist" target="Resources/GoogleService-Info.plist" />` from the plugin.xml file. However this time when I do a build action, it returns an error saying 
'Failed to apply plugin [id 'com.google.gms.google-services'] For input string: "+"'.

So anyone got idea what to do with the error and how to implement the 2 plugins together elegantly?

**Comment by sleever** [comment]
@yyzhou1994, I've currently integrated my app with AngularFire2 which, up till now, works fine.

It doesn't seem to conflict with the cordova-plugin-firebase plugin and the realtime database works as expected.

**Comment by yyzhou1994** [comment]
@sleever, How about [cordova-firebase-plugin-realtime-database](https://github.com/hbmartin/cordova-plugin-firebase-realtime-database) plugin? Have you tried that plugin with cordova-plugin-firebase before?

**Comment by DavidFrahm** [comment]
Using multiple Cordova plugins for Firebase sounds very problematic.

Just for starters:

- Contention over `GoogleService-Info.plist`
- Dependency management conflicts with required Google libraries for Play Services and Firebase

Seems like using this `cordova-plugin-firebase` plugin with AngularFire2 is the only reliable thing, so we need database support added here to get great offline capability.

**Comment by DavidFrahm** [comment]
Does the recent (May 17th, 2017) announcement of [open-sourcing the Firebase SDKs](https://opensource.googleblog.com/2017/05/open-sourcing-firebase-sdks.html) have any impact or opportunity here?

Maybe this repo should be moved under Firebase and maintained there, with realtime support added?

**Comment by apptum** [comment]
@DavidFrahm about the real time plugin: why don't you use firebase' web api? Every query/write etc works when offline and automatically syncs to the server when back online again. All you have to do is save the states to a local db which gets updated on server updates, or miss I something?

**Comment by DavidFrahm** [comment]
@apptum Well this is exactly the functionality I don't want to hand roll, and feel would help all the cordova firebase developers to have built-in to this plugin

> All you have to do is save the states to a local db which gets updated on server updates, or miss I something?

**Comment by zakton5** [comment]
@DavidFrahm @apptum I would greatly prefer to use the one liner of `Firebase.getDefaultConfig().setPersistenceEnabled(true);` as opposed to using a local db. If no one is currently working on this issue, I will gladly fork the repo and attempt it myself.

**Comment by zakton5** [comment]
I would like some input? Should I attempt to model the API after the native iOS/Android calls or more like AngularFire?

**Comment by explofish** [comment]
AngularFire now Supports Offline Functionality due to the release of FireStore (which has Offline Support even for the WEB).

Though, i have a bad feeling with having two instances of Firebase (one Native, one Web SDK), using AngularFire with cordova-plugin-firebase now seems like a good solution.

**Comment by soumak77** [comment]
closing as resolved.  AngularFire should support your needs.
