### ISSUE TITLE
.setScreenName() for iOS

### ISSUE THREAD

**Issue by ilyakar** [arnesson/cordova-plugin-firebase#168]
It seems this method is only implemented for Android devices (should be in readme). Can we also please have it for iOS?

**Comment by robertarnesson** [comment]
I'll take a PR

**Comment by NoelDeMartin** [comment]
I implemented this method only in Android because I'm not too experienced programming for iOS. I didn't indicate it in the readme because I assume it'll be implemented before doing the next release (in case it isn't it should be documented yes). You can see the status of the feature in this issue: https://github.com/arnesson/cordova-plugin-firebase/issues/98
