### ISSUE TITLE
NPE fix and request for onNotification

### ISSUE THREAD

**Issue by MeMyselfI** [arnesson/cordova-plugin-firebase#18]
A possible NPE occurs here:

public static void onNotificationOpen(Bundle bundle) {
    final CallbackContext callbackContext = FirebasePlugin.callbackContext.get();

when callbackContext is null so if there's no callbackContext is set.

Generally spoken I would use an ArrayList here so that multiple listeners can be registered...

In addition for this I want to suggest to implement a onNotification listener, which works just the same for notifications received while the app is in the foreground.

**Comment by c4software** [comment]
I confirm :

`
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
org.apache.cordova.firebase.FirebasePlugin.onNotificationOpen (FirebasePlugin.java:116)
org.apache.cordova.firebase.OnNotificationOpenReceiver.onReceive (OnNotificationOpenReceiver.java:21)
…`
