### ISSUE TITLE
hasPermission() not available in latest release.

### ISSUE THREAD

**Issue by MattDHill** [arnesson/cordova-plugin-firebase#193]
The hasPermission() method is well documented int he Readme but isn't part of the latest version 0.1.19. I'm hesitant to download directly form GitHub. When will you be releasing the next version with this method? Thx.

**Comment by xan589** [comment]
+1

**Comment by FreezyExp** [comment]
'latest release' in the title is a bit ambiguous, noting the version might be more specific.
Using a source compare tool, you can compare the github version to the release you are using.
There are some nice patches to be found if you are willing to put in the effort.

It would be nice if this github would also tag the published versions, instead of only having 'master'.

It should not be too hard to merge in only the hasPermission / getPermission code into your build.

**Comment by robertarnesson** [comment]
fixed in 0.1.20
