### ISSUE TITLE
Default FirebaseApp is not initialized issue in Android plugin

### ISSUE THREAD

**Issue by amitanmol** [arnesson/cordova-plugin-firebase#206]
Hi,

I am facing below issue in android plugin:

Default FirebaseApp is not initialized in this process com.x.xyz. Make sure to call FirebaseApp.initializeApp(Context) first.

Please suggest.

Thanks

**Comment by kotromeo** [comment]
+1
getting this on android 7

**Comment by apptum** [comment]
I faced the same problem, especially when I used the single firebase libraries like 
```
/firebase-app.js
/firebase-database.js
/firebase-auth.js
```
instead of the one big ``/firebase.js``.

I ended up writing a simple interval when I initialize firebase, like so
```
var interval = setInterval(function () {
    if (typeof firebase !== "undefined") {
        clearInterval(interval);
        firebase.initializeApp(config);
    } else {
        console.log("waiting for firebase script to load");
    }
}, 200);
```

If you really want to use the single libraries, it gets more tricky: f.e. firebase-auth.js seems to load quicker then firebase-app.js which resulted for me in errors on load when I loaded them in a <script> tag. Instead, I injected them dynamically after onDeviceReady and waited for each to be loaded. Then used the interval to wait for "firebase", then a second interval for all others.

**Comment by gauravmehta19** [comment]
+1 
on Motog as well.

**Comment by gugarush** [comment]
Same here

**Comment by andrewhmoss** [comment]
Me too, moto 4g - android 7.

**Comment by andrewhmoss** [comment]
same on pixel simulator with android 8.0

**Comment by NehaKushwah993** [comment]
did someone find solution?

**Comment by Hans-Hudson** [comment]
I had this issue, try to get the latest SDK - Google Play Services
