### ISSUE TITLE
Cordova Google Maps : error on build

### ISSUE THREAD

**Issue by tgensol** [arnesson/cordova-plugin-firebase#27]
Hi there,

My build was working and then I added cordova-plugin-googlemaps, and now I got this message when I am trying to build for android : 

`Dex: Error converting bytecode to dex:

Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;`

Looks like googlemaps and firebase plugin are not working together.
I read that I have to exclude some dependencies ? How can I do that ?
Thanks !

**Comment by tacitomv** [comment]
Hello @tgensol , I just fixed it by simply adding a cordova plugin:
[](https://github.com/jwall149/cordova-multidex)
It looks like this problem is related to "having more than 64k method calls", witch you can have when using cordovaLibs.

You can add in your config.xml, like this:
`<plugin name="me.tonny.cordova.plugins.multidex" spec="https://github.com/jwall149/cordova-multidex" />`

Or add via npm, like 
`ionic plugin add https://github.com/jwall149/cordova-multidex --save`
