### ISSUE TITLE
Cannot run on iOS

### ISSUE THREAD

**Issue by remisture** [arnesson/cordova-plugin-firebase#329]
> You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.

Is this caused by this plugin?

> Cordova CLI: 7.0.1
> Gulp version:  CLI version 3.9.0
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 1.3.2
> Ionic CLI Version: 2.0.0
> Ionic App Lib Version: 2.0.0
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v4.2.6
> Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by remisture** [comment]
Probably related to: #327
<img width="1139" alt="skjermbilde 2017-06-24 kl 15 17 06" src="https://user-images.githubusercontent.com/2372967/27508906-6622505e-58f0-11e7-9255-380c51629d7a.png">

**Comment by dhruvmishra00** [comment]
First of all thanks for this wonderful plugin...i really appreciate the work done....it took around 3 weeks to finally get notifications in my cordova app... you can try following steps in order to receive the push notification...

1. Set up you cordova app and add plugin using cordova-plugin-firebase.
2. Create a account in FCM and download google-info.plist and place it in root directory
3. Setup APNs which is very important and generate .p12 files for FCM.
4. Upload .p12 files in FCM console and now your APNs is connected to FCM
#Note: kindly enable push notification and background mode in compatibility of your project.
# kindly generate the provision profile for your app and after download double click on it for installation.
5. Now once you are done with above steps you should receive instance token..if not... u are missing something...
6. If you are receiving token, then to make build instead of testing in simulator...
# there might be some error in log of app while testing in simulator....you can resolve it...

Hope this will help you....sorry for bad english.... this plugin works fine...just stay with it 

and big thanks to developer of this plugin...

**Comment by robertarnesson** [comment]
use the latest release - 0.1.22. re-open if the problem persists
