### ISSUE TITLE
Enable Push Notifications Capability

### ISSUE THREAD

**Issue by ccorcos** [arnesson/cordova-plugin-firebase#369]
It would be great if this plugin would automatically enable the push notifications capability like they do in [this package](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/afterPrepareHook.js#L79) for associated domains.

**Comment by ccorcos** [comment]
I've created a workaround using a hook for now in case anyone else is running into this issue:

```
<hook src="./bin/push-capability.js" type="before_compile" />
<hook src="./bin/push-capability.js" type="before_run" />
```

```
const plist = require("plist")
const glob = require("glob")
const shell = require("shelljs")
const path = require("path")
shell.set("-e")

module.exports = context => {
	// Find the entitlements file using a pattern match
	const entitlementsGlob = path.join(
		context.opts.projectRoot,
		"platforms/ios/*/Resources/*.entitlements"
	)
	const entitlementsFile = glob.sync(entitlementsGlob)[0]

	// Read the entitlements file and parse into json
	const plistProperties = plist.parse(shell.cat(entitlementsFile).toString())

	// Set the Push Notifications capability
	const key = "aps-environment"
	const value = context.opts.options.release ? "production" : "development"
	plistProperties[key] = value

	// Write the file back
	shell.ShellString(plist.build(plistProperties)).to(entitlementsFile)
}
```

**Comment by jorrit-wehelp** [comment]
It already does through plugin.xml: https://github.com/arnesson/cordova-plugin-firebase/blob/master/plugin.xml#L74

I think it's more a problem with cordova-universal-links-plugin, since it writes it's own .entitlements file and configures the xcode project to use that, instead of the Entitlements-{Debug,Release}.plist files that were added in cordova-ios 4.3.
Also see https://github.com/nordnet/cordova-universal-links-plugin/issues/89
