### ISSUE TITLE
Android: logEvent does not track event value properly

### ISSUE THREAD

**Issue by chemerisuk** [arnesson/cordova-plugin-firebase#40]
I've started using the plugin and noticed that event value is not tracked for Android. I guess the cause of the issue if that during conversion to `Bundle` all attribute values serialized as strings, but the framework expects `Float` or `Long` instead in some cases.

**Comment by zwand19** [comment]
could it also be related to https://github.com/firebase/quickstart-android/issues/14? We are currently working through this in our app.

**Comment by robertarnesson** [comment]
@zwand19 no the same issue

@chemerisuk yes we should probably do some type checking and serialize each value to the right type

**Comment by CTucker1327** [comment]
in iOS all events are logged under `SELECT_CONTENT` which makes analytics practically useless.

**Comment by robertarnesson** [comment]
@CTucker1327 update the plugin to latest

**Comment by CTucker1327** [comment]
@robertarnesson Latest version available through command

```
cordova plugin install cordova-plugin-firebase
```

is

```
cordova-plugin-firebase 0.1.9 "Google Firebase Plugin"
```

Github Package.json shows 0.1.10 as the current version number.

I've had issues in the past where `0.1.9` is considered a higher version than `0.1.10` because `0.1.9` is considered `0.1.90` perhaps this is related? I'll install manually for the time being and report back after we test it out. Thanks.
