### ISSUE TITLE
 How to show notifications even with the application open. Show notification in notification bar

### ISSUE THREAD

**Issue by lepokoloko** [arnesson/cordova-plugin-firebase#435]
How to show notifications even with the application open. Show notification in notification bar

**Comment by Oz-at-Work** [comment]
Notifications don't work at all in foreground as far as I can tell.

However, if you add the following code to the bottom of Firebase.m in the plugin, notifications in foreground will be delivered to the app:

```
    - (void)messaging:(nonnull FIRMessaging *)messaging
    didReceiveMessage:(nonnull FIRMessagingRemoteMessage *)remoteMessage {
        [Firebase.firebase sendNotification:[remoteMessage appData]];
    }

    - (void)applicationReceivedRemoteMessage:(nonnull FIRMessagingRemoteMessage *)remoteMessage {
        [Firebase.firebase sendNotification:[remoteMessage appData]];
    }
```

Not 100% certain if the second of the two methods is required or not.  It says it's deprecated but then I also upgraded my Firebase frameworks, so that may be why.  

In my case `messaging:didReceiveMessage` is called when in foreground, perhaps with older frameworks `applicationReceivedRemoteMessage` is called.  

IDK, but it works for me.
