### ISSUE TITLE
getInstanceId return null 

### ISSUE THREAD

**Issue by harksin** [arnesson/cordova-plugin-firebase#45]
Please don't close an issue not resolved.

I understand your pitch, and you are right, throw error is not the way, my bad.

But in this case, return null is not the solution.
Just because this delegate plugin logic in application code, and it's not his responsibility.
Or just because null is shit like you want.

So, maybe we can think about returning a promise or an observable instead of a very limited  callback ?

**Comment by robertarnesson** [comment]
This is not an issue with the plugin itself. I added a note in the docs about it, that's as far as this will go.

Callbacks is the cordova standard, all plugins work this way. If you need promises or whatnot then add another layer on top of cordova (example: https://github.com/arnesson/angular-cordova/blob/master/plugins/3rdparty/firebase.service.ts)

**Comment by AjawadMahmoud** [comment]
is this issue about the null return or about the style of how the return works, @harksin ?
if it's first i need to second this, @robertarnesson, as we were discussing in #34. otherwise, nope, the plugin seems to work in compliance with the node-standard of callbacks and value returns.

**Comment by harksin** [comment]
The Issue is about the null return, if Cordova standard is callbacks, maybe we sould  firing  callback only if token is acquired or if there is an issue?

Furthermore, for me this appears with an  "INVALID_SENDER"  log in ddms and an infinite retry.

but my google-service.json is working correctly with Cordova-fcm-plugin

**Comment by AjawadMahmoud** [comment]
I'm not sure about the log you are getting in your console. however, the callback is the defacto of node and cordova. callbacks for the different returns cases like success and error are a must to determine whether the call is succeeded or not.
i'm not sure what cases the error callback would be used, as i can see that even a failed call is returning null on the success callback. however, talking about the callback structure, i believe it's the way it should be.

**Comment by robertarnesson** [comment]
I've been debugging this on IOS (but the issue is the same on android) - a lot of times it takes a while for the app to connect to FCM and establish a token (i've seen up to 10+ seconds). What we need is a javascript callback to listen to token changes from tokenRefreshNotification (onTokenRefresh on android). This would be the best and fastest way to get a token as soon as its available. This is on my personal todo...

**Comment by budlight** [comment]
the link to promise example above is broken

**Comment by achuinard** [comment]
@robertarnesson I've just submitted a pull request for the tokenRefreshNotification listener. It should work on iOS. I did not do the corresponding Android work, but can you take a look at iOS and if you greenlight it maybe I can get the Android stuff done too?

**Comment by nikrhes** [comment]
Hi, I got the same problem with android devices. But get instance id works perfectly on IOS. I am new with firebase, if this possible with something wrong with my configuration? Because at the end the app looks like not registered at the fire base console. I already following the tutorial in firebase website but still cant make it at least the app getting registered on firebase console.

**Comment by abunour22** [comment]
same issue here !!

**Comment by c4software** [comment]
I've got the same issue… But its appear (in my case) to be only present in debug. When i sign and publish my application (in beta or production) the problem disapear.

I'm not sure if its a problem with the plugin or the Google Side. Google backend seems ignoring the debug certificate…

**Comment by nikrhes** [comment]
Hi guys, maybe find the solution for debug certificate. first, we need to remove the android platform first then add the platform again using 'cordova platform add android'. Need to use the platform add because the other command resulting error on firebase SDK. then, i try to run the cordova through android studio, after that the code working perfectly and I got the FCM token. But after this, common cordova run and build command works fine. 

Note: if the android studio ask for gradle update, do not do it, it breaking the code as well.

**Comment by robertarnesson** [comment]
in master there is now onTokenRefresh to register a callback when the token changes (ios and android). not sure if that fixes this specific problem, but it is the best way to get a valid token as quickly as possible.

**Comment by zhkuskov** [comment]
Hi, I have this in log:
FirebaseInstanceId: background sync failed: INVALID_SENDER, retry in 20s
