### ISSUE TITLE
Crashlytics support

### ISSUE THREAD

**Issue by chinlun** [arnesson/cordova-plugin-firebase#548]
Crashlytics will soon replace Crash Reporting, any plans to upgrade this plugin for the support?

**Comment by johanlantz** [comment]
I am also super interested in this. I have spent almost 2 days on updating your projects gradle extensions to use Crashlytics but without any luck. I just keep getting strange errors about API key from Crashlytics even though everything seems correct.

It would be very interesting to know if someone plans to work on this soon since Crashlytics appears to be the way forward for Firebase crash reporting.

**Comment by Chumillas** [comment]
Crashlytics is the way forward for Firebase crash reporting. 
Hoping to see this added soon

**Comment by jcyh0120** [comment]
This would be really helpful!

**Comment by Hirbod** [comment]
Any news here @arnesson   ?

**Comment by soumak77** [comment]
No one is currently working on this.  PRs are welcome.

**Comment by tryadelion** [comment]
if i had cordova plugin making knowledge i would, but the docs are too heavy to spend so much work time on them. is there any quick guide on it?

**Comment by Wilco2998** [comment]
I have tried to add Crashlytics manually and got it to work, I only need to know how I can acces the build.gradle file in platforms/android to add the gradle dependencies.
If someone knows how to extend or acces it let me know

**Comment by remisture** [comment]
Any updates on this subject? Crashlytics support would've been great!

**Comment by guylando** [comment]
+1

**Comment by guylando** [comment]
maybe can take idea from https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics

**Comment by guylando** [comment]
also here they made a pr\update which added crashlytics support so can look at how they have done it
https://github.com/chemerisuk/cordova-plugin-firebase-crash

**Comment by ndrake** [comment]
There is an open PR to switch to Crashlytics:  https://github.com/arnesson/cordova-plugin-firebase/pull/784

**Comment by briantq** [comment]
I feel that there should be some mention of the new APIs that are offered, much less the new library dependency that is now part of this plugin in the main README, especially since it is not packaged as part of FIrebase.  I was already using another plugin to handle Crashlytics that this now conflicts with and had I not tried to update the SDK versions, I would never have known and likely would have unpredictable behaviors in the future.

**Comment by soumak77** [comment]
This has been implemented.  Version 2.0.1 (coming soon) should have Crashlytics support for android and iOS.

**Comment by canadaka** [comment]
I'm using an existing Crashlytics plugin 'cordova-fabric-plugin' and going to switch/migrate to Google Firebase. Do I need to have both plugins installed, or does this plugin handle all the Crashlytics SDK data collection?

**Comment by ios-dev-newbie** [comment]
How to use the cordova-plugin-firebase to report crash on firebase console. I tried to add above plugin and I was able to add it in my project. But after that how to setup the project for crash report was not able to understand. Can someone please provide a help.

**Comment by stewwan** [comment]
for those who are stuck with cordova, try to get capacitor.

there's a plugin for this

https://github.com/stewwan/capacitor-crashlytics
