### ISSUE TITLE
Split plugin into smaller ones?

### ISSUE THREAD

**Issue by BugsBunnyBR** [arnesson/cordova-plugin-firebase#554]
Hi, Would it be possible to split the plugin into others? Like each feature notifications, analytics, event tracking, crash reporting... could have it own plugin.
The current approach works, but I think multiple people may be using some of the features here, but not others and Firebase native libs are not so small. The split of the plugin into smaller peaces would help us to have move control over what is being packed in each app.

**Comment by tomhartz** [comment]
@BugsBunnyBR There are other plugins out there that offer subset of Firebase features.

Notifications: https://github.com/fechanique/cordova-plugin-fcm
Analytics: https://github.com/chemerisuk/cordova-plugin-firebase-analytics

Not sure if either of these two are individual pieces you are looking for.  BTW, I have migrated over to this arnesson version because of conflicts between the above.

**Comment by BugsBunnyBR** [comment]
I just made the suggestion because I only use the notification. Not all the other stuff.

**Comment by soumak77** [comment]
closing as won't fix
