### ISSUE TITLE
Unwanted PERMISSIONS added automatically

### ISSUE THREAD

**Issue by ragcsalo** [arnesson/cordova-plugin-firebase#619]
In the latest release, these permissions are added automatically to AndroidManifest.xml:

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

I don't want to bother my users with asking for these unnecessary permissions.
How can avoid getting these permissions added automatically?

**Comment by vantezzen** [comment]
Which permissions do you mean? Firebase needs certain permissions to function so they are not "unnecessary"

**Comment by ragcsalo** [comment]
I have pasted them but they disappeared... so here they are again:

```
android.permission.WRITE_EXTERNAL_STORAGE
android.permission.READ_PHONE_STATE
android.permission.READ_EXTERNAL_STORAGE
```

These permissions were not added in previous versions... but now they are. Can I get rid of them?

**Comment by fpajor** [comment]
Same issue here, downgrading to old plugin version doesn't fix it.

The new permissions such as READ_PHONE_STATE are still there.

**Comment by JulienSopheos** [comment]
Same here.
I've looked a bit and it's seems that a `the za.co.twyst` package have a minSdkVersion < 4

	ADDED from [com.google.firebase:firebase-auth:11.8.0] C:\www\ionic-agenda\platforms\android\build\intermediates\exploded-aar\com.google.firebase\firebase-auth\11.8.0\AndroidManifest.xml:24:13-85
	android:uses-permission#android.permission.READ_PHONE_STATE
	IMPLIED from C:\www\ionic-agenda\platforms\android\AndroidManifest.xml:2:1-73:12 reason: za.co.twyst has a targetSdkVersion < 4

In the za.co.twyst Manifest the minSdkVersion is indeed < 4

    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="za.co.twyst"
        android:versionCode="1"
        android:versionName="1.0" >

        <uses-sdk android:minSdkVersion="1" />

    </manifest>


Tried some hooks to remove the permission but without success

I've also tried to edit the config.xml to add (with the correct xmlns)

    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove">


But i'm still having this issue. I'm running out of idea.

**Comment by amirhammad** [comment]
Do you use cordova-plugin-googlemaps? I am and it had caused me this problem.

tbxml-android.aar is present in platform/android/libs/tbxml-android.aar

1. unzip it
`unzip -d XYZ platform/android/libs/tbxml-android.aar`
2. Modify the following line. "XYZ/AndroidManifest.xml"
`<uses-sdk android:minSdkVersion="1" />`
to
`<uses-sdk android:minSdkVersion="4" />` 
In this i used 4. Actually I've changed this number to 16, since I don't need support for < 16.
3. rezip all the files. In **XYZ** execute the following command. It will create tbxml-android.zip
```
zip tbxml-android * 
```
4. replace the original tbxml-android with the new file
`cp XYZ/tbxml-android.zip platform/android/libs/tbxml-android.aar`

This fix should be probably done in googlemaps repository, so we don't have to hack it like this :'(

**Comment by soumak77** [comment]
Not sure there is a fix we can apply here.  Please reopen and submit a PR if there is something we can do to fix this.
