### ISSUE TITLE
Plugin update issue 

### ISSUE THREAD

**Issue by sadjous** [arnesson/cordova-plugin-firebase#671]
when i try to update this plugin to 1.0.3 i faced some difficulties.

- When i run `cordova plugin add cordova-plugin-firebase` it take too long time and the plugin is not installed 

- but if i run `cordova plugin add [some_plugin]` it work fine

- by checking i try to download the `.zip` file of the plugin from the repository and i found that it's around 126 MB

it's so strange, am i wrong doing some thing or it's the plugin new size

please help

thank for your help and i'm sorry for my english

**Comment by soumak77** [comment]
It appears this plugin has issues installing on slow networks due to the large plugin size as you mentioned.  The plugin has to include the Firebase iOS SDK, causing the plugin download size to balloon up to over 100 MB.  An alternative is to install the Firebase iOS SDK via CocoaPods, but I'm not sure how that will affect other users.

**Comment by soumak77** [comment]
this will be fixed with #672.  Until then, just try to reinstall until it works.

**Comment by ayyazzafar** [comment]
I am also facing this issue. I am waiting since 2 hours but installation is still not completed. :(
