### ISSUE TITLE
Support for Firebase Cloud Firestore with DB and Authentication for Ionic.

### ISSUE THREAD

**Issue by alecsawatzky** [arnesson/cordova-plugin-firebase#747]
Hello, does this plugin work in a hybrid ionic project? My intention is to use an API that has support for Firebase Cloud Firestore database and authentication with offline access of data and credentials that would work on Android, IOS, and a PC's web browser.

**Comment by soumak77** [comment]
suggestion is to use https://github.com/angular/angularfire2

**Comment by sengoontoh** [comment]
The underlying indexeddb implementation of Firestore that's also inherited by angularfire2 feels really flaky to me. I'm getting lots of async queue failures. My app also occasionally does not resume gracefully from background mode. I'm speculating because the indexeddb drivers still work in background but the webview is just hibernated.

It would be really awesome if we can just use native iOS/Android Firebase SDK's for database functionality. What's blocking this?
