### ISSUE TITLE
Firebase + AdmobFree plugin causes failed task :app:transformClassesWithDesugarForDebug

### ISSUE THREAD

**Issue by baron554** [arnesson/cordova-plugin-firebase#761]
https://github.com/ratson/cordova-plugin-admob-free
https://github.com/arnesson/cordova-plugin-firebase/

When both of these plugins are used together the app:transformClassesWithDesugarForDebug task will fail. I have not found a way to fix this. The error log is provided below in the stack overflow link.

I have documented the issue at: https://stackoverflow.com/questions/51179005/execution-failed-for-task-apptransformclasseswithdesugarfordebug-cordova-gra

**Comment by baron554** [comment]
@robertarnesson  would you be able to take a look into this?

**Comment by aktet** [comment]
cordova-plugin-admob-free  have dependency cordova-admob-sdk open  [plugin.xml](https://github.com/rehy/cordova-admob-sdk/blob/master/plugin.xml) and change 
`<preference name="PLAY_SERVICES_VERSION" default="11.0.4"/>` to `<preference name="PLAY_SERVICES_VERSION" default="+"/>`

Or read this [read me ](https://github.com/arnesson/cordova-plugin-firebase/blob/master/README.md)

> Google Play Services
Your build may fail if you are installing multiple plugins that use Google Play Services. This is caused by the plugins installing different versions of the Google Play Services library. This can be resolved by installing cordova-android-play-services-gradle-release.

**Comment by soumak77** [comment]
closing as resolved, see above comment
