### ISSUE TITLE
Ionic V4 error: ERROR in node_modules/@ionic-native/firebase/index.d.ts(2,10): error TS2305:

### ISSUE THREAD

**Issue by alphapilgrim** [arnesson/cordova-plugin-firebase#783]
> [ng] ERROR in node_modules/@ionic-native/firebase/index.d.ts(2,10): error TS2305: Module '"/node_modules/rxjs/Observable"' has no exported member 'Observable'.
> [ng] node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

npm version 6.2.0
ionic version 4.0.1

**Comment by onkar0777** [comment]
I struggled with this error for more than a day and finally solved it. It is majorly because when you add native plugins from ionic it fetches that latest stable version which does not work with the latest ionic 4 beta version.
So you need to add the corresponding beta version for ionic native as well. So you need to run this:
1. npm install @ionic-native/core@5.0.0-beta.14
2. npm install @ionic-native/firebase@5.0.0-beta.14

Then other important thing is to note that for angular the import of ionic native plugins in app module also has changed, so you will have to make the following change in you app.module:

import { Firebase } from '@ionic-native/firebase**/ngx**';

Then it should run fine. Hope this helps! 👍

**Comment by alphapilgrim** [comment]
@onkar0777 thanks for the update, I'm still getting a compile error. Any idea's?

`[ng] ERROR in src/app/app.module.ts(8,26): error TS2307: Cannot find module '@ionic-native/firebase**/ngx**'.`

**Comment by onkar0777** [comment]
I would guess that you did not run `npm install @ionic-native/firebase@5.0.0-beta.14`

Also I am not sure what is ** in @ionic-native/firebase**/ngx**

**Comment by soumak77** [comment]
closing as resolved

**Comment by fpassa** [comment]
this error still appearing with ionic-native/admob 4.20.0 and ionic-native/core 5.2.0
when doing:
$ ionic cordova plugin add cordova-admob
$ npm install --save @ionic-native/admob@4

ERROR in node_modules/@ionic-native/admob/index.d.ts(2,10): error TS2305: Module '"/Users/flavio/Quizionic4/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Comment by ssj7** [comment]
> 
> 
> this error still appearing with ionic-native/admob 4.20.0 and ionic-native/core 5.2.0
> when doing:
> $ ionic cordova plugin add cordova-admob
> $ npm install --save @ionic-native/admob@4
> 
> ERROR in node_modules/@ionic-native/admob/index.d.ts(2,10): error TS2305: Module '"/Users/flavio/Quizionic4/node_modules/rxjs/Observable"' has no exported member 'Observable'.
> node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

`npm install --save rxjs-compat`
As Rxjs is required for Angular 6 using in Ionic 4.
