### ISSUE TITLE
AndroidStudio.js:inAndroidStudioProject root does not exist:  Helpp !

### ISSUE THREAD

**Issue by wirendy** [arnesson/cordova-plugin-firebase#818]
Last Week, i still use cordova-plugin-firebase 1.0.5 and still work, now if i want to build app, i cant,
so i think i must re-add platform and then error appear

Error: uh oh
AndroidStudio.js:inAndroidStudioProject root does not exist:

**Comment by soumak77** [comment]
Nothing we can do without more info.  Please reconfirm issue persists with v1.1.3 and provide full logs to be investigated.

**Comment by Cirivas** [comment]
Run into this problem this day. What I did was remove Android platform, uninstall the plugin from other platforms (e.g ios), add android again and install the latest version of the plugin.

**Comment by herrskytte** [comment]
If you try to remove the cordova-plugin-firebase to test a new version, the entire android platform is broken, all files except a few remains. Fix is to remove and add platform, but this can be a problem if you do changes in platform

**Comment by briantq** [comment]
@herrskytte Agreed that the upgrade can be an issue but this is a limitation of Cordova. Based on the Cordova documentation https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/ it's recommended that you do NOT make changes in the platform. I have found if you need to make changes (at least for my use cases so far) that I can create a custom plugin to make the change. This way I can just run cordova prepare and it will be ready to go with minimal checked in files.

The other advantage is that you automatically get platform updates automatically since you don't check in the platform files. 

Not saying it's the only way to do it, but if your use cases allow leveraging the best practices, this won't be an issue

**Comment by soumak77** [comment]
closing as fixed.  @wirendy please reopen if you still experience issues after following @Cirivas's comment
