### ISSUE TITLE
screenName not working for ios.

### ISSUE THREAD

**Issue by newuser44** [arnesson/cordova-plugin-firebase#828]
New to this all.  
calling the firebase service setScreenName("Login");
This seems to work fine on android, but on ios we are not seeing the firebase_screen parameter. 
In Firebase Analytics  go to events, go to screen view,  filter by ios  and change user engagement to screen name.  We see Screen Class "(not set)" % 100%. 
Its like it got the data, but doesn't know the class to group it with?

**Comment by newuser44** [comment]
Both posted the same bug.  
In xcode while running the app,  I'm seeing the message
"setScreenName:screenClass: must be called from the main thread to ensure that the events are associated with the intended screen."  
???

**Comment by briantq** [comment]
What version of the plugin are you using?

**Comment by newuser44** [comment]
Looks like its 1.1.3   
Not sure the best way to find that out.

**Comment by briantq** [comment]
@newuser44 Running `cordova plugin list` should give you a list of the plugins you have installed and their version

**Comment by newuser44** [comment]
I updated my last comment

**Comment by briantq** [comment]
@newuser44 Thanks for that.  I don't have the time to dig into what the issue/fix for this is, but the code you are looking for on iOS is in FirebasePlugin.m, specifically the setScreenName method.  It seems pretty straight forward, but if you can figure out what we might need to change to resolve the error, I would be happy to review a Pull Request and get it fixed in the plugin.

**Comment by soumak77** [comment]
@newuser44 you might want to try an updated version of the plugin.  https://github.com/arnesson/cordova-plugin-firebase/pull/751 was merged recently which fixed an issue with `setScreenName` on iOS.

**Comment by soumak77** [comment]
closing as fixed
