### ISSUE TITLE
IOS: Push notifications work only in background

### ISSUE THREAD

**Issue by Neustart** [arnesson/cordova-plugin-firebase#864]
I spent a lot of time trying to make it works without success. 
For some unknown reasons I able to receive notifications only when iPhone locked. 
Does somebody have any tricks on how to make it works?
I using version 1.0.5 or 2.0.1. The same problem for both of them. 
I had absolutely the same problem with another plugin [cordova-plugin-fcm](https://github.com/fechanique/cordova-plugin-fcm). Any idea what is going on ?

**Comment by briantq** [comment]
@Neustart I have not seen that before.  I have seen that push notifications only work in the foreground but have not seen it the other way around.  You might look at placing break points in the code.  I would start with the AppDelegate+FirebasePlugin.m and the FirebasePlugin.m.  I think that is going to be best way to resolve your issue since it is working for others.

**Comment by Neustart** [comment]
@briantq  `AppDelegate+FirebasePlugin.m` don't even receive those messages. Finally I've found a reason. Another plugin `parse-push-plugin` grab all my notifications for some reasons. Thanks a lot.

**Comment by briantq** [comment]
@Neustart Glad you were able to figure it out!
