### ISSUE TITLE
Android build fails because it suddenly can't find com.google.gms:google-services:4.1.0

### ISSUE THREAD

**Issue by phal0r** [arnesson/cordova-plugin-firebase#969]
**Describe the bug**
Without any prior changes, the Android build fails since today.

**To Reproduce**
Normal install

**Expected behavior**
Build should just run smoothly-

**Plugin Version**
2.0.5 (latest release)

**Additional context**
I just want to replicate the issue from another hybrid plugin for firebase:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1072

explanation: ```TL;DR: Google unpublished the dependency from their maven repo, so we need to have the plugin add another maven repo during the build.```

There they suggest to change the repos. I think the same needs to be done here aswell.

**Comment by troydcthompson** [comment]
Same here

**Comment by zabaat** [comment]
Did you try the suggestion at the bottom of the readme:

Google Play Services
Your build may fail if you are installing multiple plugins that use Google Play Services. This is caused by the plugins installing different versions of the Google Play Services library. This can be resolved by installing cordova-android-play-services-gradle-release.

If your build is still failing, you can try installing cordova-android-firebase-gradle-release. For more info, read the following comment about locking down the specific versions for play services and firebase. It is suggested to use + instead of 15.+ to ensure the correct versions are used.

**Comment by phal0r** [comment]
@zabaat 
Thanks for your answer. This is not a problem with dependency conflicts, but google accidently depublished some dependencies necessary for firebase, thus giving build errors. This mistake was aknowlegeded and is now fixed.

Here is a official statement: https://issuetracker.google.com/issues/120759347#comment36

Since it is resolved by google I will close this now.
