### ISSUE TITLE
Cannot read property 'toString' of null when using Phonegap build fix

### ISSUE THREAD

**Issue by weislanes** [arnesson/cordova-plugin-firebase#99]
I'm trying to build an Android APK and followed the instructions to make this work on Phonegap build but am getting the error 'Cannot read property 'toString' of null' when I run a method.

Looks like it can't find a file yet I've copied google-services.json into 'src\android' manually as per the instructions. 

Any ideas?

**Comment by robertarnesson** [comment]
phonegap build is not supported. the note in the readme is just a suggestion and not a complete solution. since hooks do not work in PGB, you will have to manually implement what the hook would otherwise do for you. This includes copying files and setting the correct api ids and keys.

We do not use or support PGB so you are on your own

**Comment by jvwelzen** [comment]
Thx got it working on phonegap build :-)

**Comment by robertarnesson** [comment]
I updated the readme, hope it helps

**Comment by thienanle** [comment]
@jvwelzen apologies in advance, I know this topic is quite old. Would you mind sharing what you had to do to get it working on PhoneGap Build? I copied the config files over, but it seems the hooks do a lot more than that (e.g. editing build.gradle).

**Comment by jvwelzen** [comment]
@thienanle Already got it working ?

**Comment by jvwelzen** [comment]
Sorry for my late response btw ;-(
